# Generated by Django 3.2.2 on 2021-05-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contacts', models.CharField(max_length=64)),
                ('rcv_address', models.CharField(max_length=64)),
                ('postal_code', models.CharField(max_length=32)),
                ('user_phone', models.CharField(max_length=64)),
                ('shop_time', models.DateTimeField(auto_now_add=True)),
                ('money', models.FloatField(max_length=11)),
                ('state', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('admin', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64, null=True)),
                ('postal_code', models.CharField(max_length=32, null=True)),
                ('phone', models.CharField(max_length=64, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('state', models.CharField(max_length=64, null=True)),
                ('reg_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_id', models.IntegerField()),
                ('commodity_name', models.CharField(max_length=64)),
                ('price', models.FloatField(max_length=11)),
                ('shop_number', models.IntegerField()),
                ('user_info', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.user_info')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_id', models.IntegerField()),
                ('commodity_name', models.CharField(max_length=64)),
                ('price', models.FloatField(max_length=11)),
                ('shop_number', models.IntegerField()),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.user_info'),
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('commodity_name', models.CharField(max_length=64)),
                ('factory', models.CharField(max_length=64)),
                ('info', models.CharField(max_length=64)),
                ('price', models.FloatField(max_length=11)),
                ('img_name', models.CharField(max_length=64)),
                ('stock', models.IntegerField()),
                ('shop_number', models.IntegerField()),
                ('click_number', models.IntegerField()),
                ('state', models.CharField(max_length=64, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('com_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.commodity_type')),
            ],
        ),
    ]
