# Generated by Django 3.2.2 on 2021-05-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commodity',
            new_name='Store_Commodity',
        ),
    ]
