# Generated by Django 3.2.2 on 2021-05-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_commodity_store_commodity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store_commodity',
            name='info',
            field=models.CharField(max_length=128),
        ),
    ]
